services:
  - type: web
    name: memory-game-backend
    env: node
    rootDir: apps/backend
    buildCommand: pnpm install --frozen-lockfile && pnpm run build && pnpm run db:migrate:deploy
    startCommand: NODE_ENV=production pnpm start --filter=@memory-game/backend
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: PRISMA_ACCELERATE_URL
        sync: false
