services:
  - type: web
    name: memory-game-backend
    env: node
    rootDir: apps/backend
    buildCommand: cd ../.. && pnpm install --frozen-lockfile && pnpm turbo build --filter=backend... && pnpm turbo db:migrate:deploy --filter=@memory-game/database
    startCommand: cd ../.. && pnpm start --filter=backend
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: PRISMA_ACCELERATE_URL
        sync: false